# This is the configuration used to check the rubocop source code.

# TODO: activar
# require: rubocop-rspec

Layout/LineLength:
  Max: 100

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 150
Metrics/ClassLength:
  Max: 210

# RSpec/MultipleMemoizedHelpers:
#   Enabled: false
# RSpec/ContextWording:
#   Enabled: false
# RSpec/NestedGroups:
#   Max: 7
# RSpec/MultipleExpectations:
#   Max: 5

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/Semicolon:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false

AllCops:
  # DisabledByDefault: true
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'config/routes.rb'
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'scripts/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
