# exclude:
#   - 'exclude/files/in/this/directory/from/all/linters/**/*.slim'

linters:
  # EmptyControlStatement:
  #   exclude:
  #     - 'app/views/directory_of_files_to_exclude/**/*.slim'
  #     - 'specific/file/to/exclude.slim'
  LineLength:
    max: 130
    # include: 'specific/directory/to/include/**/*.slim'

  # RedundantDiv:
  #   enabled: false
