
default: &default
  host: localhost
  port: 5432
  username: template_pg
  password: template_pg
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: 5



development:
  <<: *default
  database: template_pg_development

test:
  <<: *default
  database: template_pg_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
