
default: &default
  host: localhost
  port: 5432
  username: eldesasosiego
  password: eldesasosiego
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: 5



development:
  <<: *default
  database: eldesasosiego_development

test:
  <<: *default
  database: eldesasosiego_test


