toolbar:
  - image | link | media | uploadimage
  - formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat'
plugins:
  - media
  - image
  - link
  - imagetools
  - table
  - spellchecker
  - uploadimage