# frozen_string_literal: true

# == Schema Information
#
# Table name: paginas
#
#  id         :bigint           not null, primary key
#  numero     :integer
#  texto      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# generado con pg_rails

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe PaginasController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Pagina. As you add validations to Pagina, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    attributes_for(:pagina)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaginasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:user) { create :user, :admin }

  before do
    sign_in user
  end

  describe 'GET #index' do
    it 'returns a success response' do
      create(:pagina)
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      pagina = create(:pagina)
      get :show, params: { id: pagina.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      pagina = create(:pagina)
      get :edit, params: { id: pagina.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Pagina' do
        expect do
          post :create, params: { pagina: valid_attributes }, session: valid_session
        end.to change(Pagina, :count).by(1)
      end

      it 'redirects to the created pagina' do
        post :create, params: { pagina: valid_attributes }, session: valid_session
        expect(response).to redirect_to(Pagina.last)
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        attributes_for(:pagina)
      end

      it 'updates the requested pagina' do
        pagina = create(:pagina)
        put :update, params: { id: pagina.to_param, pagina: new_attributes }
        pagina.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the pagina' do
        pagina = create(:pagina)
        put :update, params: { id: pagina.to_param, pagina: valid_attributes }
        expect(response).to redirect_to(pagina)
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested pagina' do
      pagina = create(:pagina)
      expect do
        delete :destroy, params: { id: pagina.to_param }
      end.to change(Pagina, :count).by(-1)
    end

    it 'redirects to the paginas list' do
      pagina = create(:pagina)
      delete :destroy, params: { id: pagina.to_param }
      expect(response).to redirect_to(paginas_url)
    end
  end
end
